// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.softtek.gestionhrapi.dominio;

import java.io.Serializable;

privileged aspect ContactosPK_Roo_Serializable {
    
    declare parents: ContactosPK implements Serializable;
    
    private static final long ContactosPK.serialVersionUID = 1L;
    
}
